### ISSUE TITLE
ESDoc Hosting Service

### ISSUE THREAD

**Issue by h13i32maru** [angie-framework/angie#4]
Hi!
I am ESDoc developer and thanks for using ESDoc :smile: 

I released [ESDoc Hosting Service](https://doc.esdoc.org) :rocket: 
Register your repository Git URL, this service automatically generate documentation.
If you are interested, please try to use it.
Thanks

**Comment by benderTheCrime** [comment]
Ryo,

How are you doing? I am not looking to have my documentation hosted, I serve it through Github. Are you looking for contributors on the ESDoc project? It looks like it will be a pretty important project as I have not found another comparable library out there yet.

Regards,
JCG (@benderTheCrime)

**Comment by benderTheCrime** [comment]
This is not an issue, but a shameless plug. Please use this section only for actual issues.
